export const products = [
  {
    id: 1,
    title: "Capymate",
    price: 750,
    description: "Mate de carpincho impreso en 3D",
    category: "mates",
    img: "",
  },
  {
    id: 2,
    title: "Carpinchomate",
    price: 950,
    description: "Mate de carpincho impreso en 3D",
    category: "mates",
    img: "",
  },
  {
    id: 3,
    title: "Gort Mate",
    price: 1250,
    description: "Mate de carpincho impreso en 3D",
    category: "mates",
    img: "",
  },
  {
    id: 4,
    title: "Figura Carpincho Mamadisimo 3D",
    price: 2000,
    description: "Figura de carpincho impreso en 3D",
    category: "figuras",
    img: "",
  },
  {
    id: 5,
    title: "Figura Carpincho Mamadisimo Plusultra 3D",
    price: 3000,
    description: "Figura de carpincho Mamadisimo 3D",
    category: "figuras",
    img: "",
  },
  {
    id: 6,
    title: "Figura Carpincho Duro 3D",
    price: 4000,
    description: "Figura de carpincho Mamadisimo 3D",
    category: "figuras",
    img: "",
  },
];
